### PR TITLE
DISCO-6 Hide Osano when embedded

### PR DESCRIPTION
**Pull request by Dantemss**
I'll change assignments and assessments to add an "embedded" class to the body when `embedded=true` is passed. Alternative is something more specific like hide-osano but I'm not sure that's needed.

### CODE REVIEW

**Review by TomWoodward — CHANGES_REQUESTED** [review]
i'm liking the "not osano specific" idea, but i think "embedded" might be too generic. because like, all of assignable is embedded and we still need to run consent somewhere.

maybe `os-subcontent` or something at least _openstax_ specific would be more appropriate

**Comment by Dantemss** [comment]
@TomWoodward I was also setting this class on the body in assignments/assessments based on the `embedded=true` parameter. Is that part still fine or would you rather I add something new?

**Review by TomWoodward — APPROVED** [review]

**Comment by TomWoodward** [comment]
@Dantemss i just found this PR in my notifications, we should merge it but its already deployed right?

**Comment by Dantemss** [comment]
It seems like this is not in prod at least. But is Rex working fine in Assignable in prod without this?

**Comment by Dantemss** [comment]
I created a staging reading assignment and I don't see Osano at all when looking at the reading, even though the osano.css that is loaded there does not have this entry. So maybe it's not needed?

**Comment by TomWoodward** [comment]
Oh yea for rex we changed the embed to not load any data and disabled osano, so maybe we can just close this now

**Pull request closed without merging**
